[package]
name = "geniex-rs"
version = "0.1.2"
edition = "2021"
description = "Safe, idiomatic Rust bindings for the Qualcomm GenieX C API (LLM & VLM inference runtime on Snapdragon)"
license = "BSD-3-Clause"
repository = "https://github.com/Maki-Grz/geniex-rs"
keywords = ["qualcomm", "geniex", "llm", "bindings", "vlm"]
categories = ["api-bindings", "hardware-support"]
authors = ["Qualcomm Technologies, Inc.", "GenieX Rust Community Contributors"]
readme = "README.md"
documentation = "https://geniex.aihub.qualcomm.com"
autoexamples = false
exclude = [
    "*.gguf",
    ".github/",
    "sandbox/",
    "assets/",
    "models/",
    "target/",
    "examples/",
]

[lib]
name = "geniex"

[dependencies]

[build-dependencies]
bindgen = "0.72.1"

[workspace]
members = [
    ".",
    "examples",
]
